// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/LucaCtt/thelist/common"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Search provides a mock function with given fields: name
func (_m *Client) Search(name string) ([]*common.Show, error) {
	ret := _m.Called(name)

	var r0 []*common.Show
	if rf, ok := ret.Get(0).(func(string) []*common.Show); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*common.Show)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
